### ISSUE TITLE
Update the family situation

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#176]
- [x] Remove the information about the brothers (number of brothers and sisters, both in France and abroad). In fact, they don't care about this information

- [ ]  Specify the number of children. We have to know **both in France and abroad**: 
- the number of minor children  
-  the number of major children  
- the number of married children

- [x] Add the number of dependents (_personnes à charge_), infact we have 2 types of information to store -> the number of adult or child 14 y.o or over in the family AND the number of child under 14 y.o . These informations are  used to compute the RUC (_revenu par unité de consommation_) (see #179 )

- [x] Add a boolean : One-parent family (famille monoparentale) used to compute the RUC (_revenu par unité de consommation_) (see #179 )

**Comment by jnizet** [comment]
Regarding the number of depenents, I don't think this belongs to the family situation:
 - where would we put it? in France, or abroad?
 - AFAIK, a person can have dependents that are not of his family

So I would just put that information elsewhere, directly in the person information (under the fiscal information, since that's a fiscal-related information, AFAIK)

Regarding the number of minor/major/married children, isn't it a bit weird? Because minors often become majors, and singles often become married or vice-versa, so that information changes often, which means that when globe will do something with that information, it has a good chance of being obsolete and wrong, and they will thus have to ask the person if the information is still correct anyway. So is it worth storing it?

**Comment by acrepet** [comment]
I've asked Globe 42 for clarifications

**Comment by acrepet** [comment]
I've just updated the description with the new elements

**Comment by jnizet** [comment]
So that I understand, do we agree on the following points?

1. The number of children in the family situation doesn't have a direct relationship with the number of dependants: some children might not be dependants (because they're independant, or taken care of by someone else, for example), and some dependants might not be children. So the family situation and the number of dependants will be filled in two separate, independant parts of the app.

2. In the family situation, we just ask the number of children in those three categories, and have thus no actual way of knowing the number of children: some are major but not married, some are minor and married, etc. The fact that they can belong to several categories is confusing, IMO. The term "married" is also confusing. Does a PACS count as "married"? I guess they know what they're talking about, but I still fear that they wouldn't all fill the form the same way.

3. The RUC part belongs to the resources section, where we should add a section about the dependants in addition to incomes and charges, and thus be able to compute the RUC in addition to the "incomes - charges" total.

4. This is actually a question about the RUC, but it's related, so I'll ask it here: is the formula really "monthly income / number of consumption units", or is it rather "monthly (income - charges) / number of consumption units"?

**Comment by acrepet** [comment]
1. You're right : a person can have dependents that are not of his family, so yes the family situation and the number of dependants will be filled in two separate

2. I still do not have clear answers about the number of children in three categories ;-( the question is still pending in trello. My proposal in Trello was (sorry for the copy/paste in French) : "Petit problème : les enfants mineurs à un instant A deviendront majeurs à un instant B. Et vous n'allez pas vous taper toutes les mises à jour (changer le nombre d'enfants quand un d'entre eux devient majeurs). Même chose pour les enfants mariés, ça risque de beaucoup changer et vous obliger à maintenir ce genre d'infos.
Propostion : Ne peut-on pas plutôt mettre la date de naissance pour les enfants? Et peut-on ne pas mettre le nombre d'enfants mariés?"

3. The RUC has to be computed in the resources section, right! But the dependants IMHO have to be in the member section (because it could have other usages I guess). I can ask them!

4. No : to compute the RUC, we have to divide the monthly income by the number of consumption units! We do not have to take in account "income - charges". This is an official rule by the CAF (like "le quotient familial"), so the charge are not to be taken in account

**Comment by jnizet** [comment]
The current family situation design is not very adequate anymore, IMHO. And it clutters the person edition form and makes it more complex than necessary.

Here's what I suggest:
1. We remove the family situations from the person edition form
2. In the person details page, in the section "Family situation", we either have no family situation, or we have one. In any case, we have a link to create/modify it. And we can delete it if it's present.
3. We model the family situation as an optional OneToOne with Person
4. In the edition form, we display something like this:
```
Parents:         [] en France  [] au Pays
Epoux(se):       O pas d'époux(se)  O en France  O au Pays
Enfants :        Prénom: ______  Date de naissance: _____  O En France  O Au Pays  [Supprimer]
                 [Ajouter]           
```

It makes the design simpler. It makes it possible to easily "move" a child from France to abroad and vice-versa. It avoids allowing to have a spouse both in France and abroad  at the same time (I assume there is no polygamy. If there has to be, then we can replace the radio buttons by checkboxes).
If the persons don't want to provide the first names, they can just use A, B, C, but at least it makes it possible to identify them.

In the person details page, we can still display two sections "France" and "Abroad" as we're doing currently.

What do you think?

The hardest part will be to migrate the data from the current design to the new one, but we can do that in Java if necessary.

**Comment by acrepet** [comment]
Such a good thing to remove the family situations from the person edition form ! Person edition form has to be definitely simpler!
I totally agree to model the family situation as an optional OneToOne with Person !
OK for your UX proposals of the person details page and the edition form.
