### ISSUE TITLE
[Person Form] Generate the 'mediation code' in the Person form

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#41]
in the Person form we can generate the "code mediation" : this is the first letter of the ~~firstname~~ last name + an incremental number.
Ex : 
Ali Mohad -> code mediation : M1
Farza Mihoud -> code mediation : M2
Mohamed Mourzi -> code mediation : M3
etc.

**Comment by jnizet** [comment]
Is it the first name, or the last name (your example suggests the last name)? What happens if the first letter of the name changes (because the user made a typo, for example). Do we also change the mediation code, or is it immutable? 
Is it needed to have a sequence per letter, or can we use the same sequence for everyone (in which case, we could simply use the ID of the person as mediation code)?

And, for my own curiosity, what is that code useful for?

**Comment by acrepet** [comment]
sorry for the mistake : it's the lastname!
this code mediation is not immutable : if the first letter of the name changes, we could change the "code mediation". 
Currently the social helpers of globe42 use a sequence per letter. As they have around 200-300 persons already in their excel spreadsheets with this algorithm (a sequence per letter) for this "code mediation", I think it's better to keep the same.
For your curiosity : when you are in a permanence of the social helpers (permanence to help and welcome migrants), they are 4 or 5 in the same room (with just decorative screens to separate their offices), they don't use the last name or the first name of the migrants, they use this code, to preserve the anonymity of these people. And during their conversation, outside these permanences, they use also this code. After weeks, they perfectly know that Farza Mihoud, for example, is M2. It's curious, but it's their practice. and because of this, I think it's better to use a sequence per letter for this code, It could be easier to remember it.

**Comment by jnizet** [comment]
OK. I thought that's what nick names were for. 

What I suggest is thus the following design:

- we create one database sequence per uppercase latin letter (from A to Z)
- when a person is created, we uppercase the first letter of the last name, and default to Z for the unlikely case that the last name doesn't use latin letters or the user has used accents or whatever, we get the next value for the corresponding sequence, and we store the generated code in the person.
- when a person is updated, we apply the new algorithm to the new name to find the letter. If it hasn't changed, we leave the mediation code as is. Otherwise, we change it.

Does that sound OK to you?

**Comment by acrepet** [comment]
Perfect! it's OK for me!

(Nick names are different : they are the usual name chosen by the migrants. Some of them (the majority) don't like to use their real first name in their daily life (outside Globe42), especially since their arrival in France, they prefer a nick name, like Momo for Mohamed, or Marcel for Mohamed (some of them chose french first names), or JB for Jean-Baptiste ;-) )
