### ISSUE TITLE
Add details on a Person

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#5]
Add these details : 

- [x] type de logement (enum : F0/F1/F2/F3/F4F5/F6+)
- [x] surface_logement (en m2)
- [x] Situation_Fiscale (enum : Imposable/Non Imposable/Non Déterminée)
- [x] situation_fiscal_a_jour (Boolean)
- [x] date_mise_en_place_situation_fiscale
- [ ] Carte_Sejour (relation many-to-one vers l'entité Carte_Sejour)
- [ ] Quartier (relation many-to-one vers l'entité Quartier)
- [x] Statut (enum : marié/ veuf/ divorcé/ celibataire/ separé)
- [x] Conjoint (relation one-to-one vers l'entité User)
- [x] Ressource (relation many-to-many vers l'entité Ressource)
Des infos concernant la Situation Familiale :
- [x] des parents en France?
- [x] des parents au Pays d'origine?
- [x] un epoux/une épouse en France?
- [x] un epoux/une épouse au Pays d'origine?
- [x] nombre d'enfants dans le pays d'origine
- [x] nombre d'enfants en France
- [x] nombre de freres ou soeurs dans le pays d'origine
- [x] nombre de freres ou soeurs en France

**Comment by jnizet** [comment]
@acrepet @cexbrayat I have started working on this issue and the related frontend issue. See #65.

Please tell me what you think about the structuring.

I didn't add the following information yet:

 - carte séjour: I have no idea what this should contain, and why there should be an entity, and even less a ManyToOne (multiple persons sharing the same card?). Shouldn't it be just a flag, or a validity date?
 - quartier: we already have the address. Isn't it redundant to add a quartier? What is this information used for? If the goal is to know where the address is located, isn't the postal code already giving that information? Or couldn't we instead geocode the address and show it on a map?
 - conjoint: I assume the association is to person, not user. But even then, is this information really useful? I'm not a big fan of using a OneToOne, since that would bring a circular dependency between persons, and potential inconsistencies: A is in couple with B, but B is not, for example. If this is really useful, I would rather add a separate entity called Couple.

@acrepet if you have answers...
