### ISSUE TITLE
JSON parse error - CityDTO 

### ISSUE THREAD

**Issue by acrepet** [Ninja-Squad/globe42#79]
Test #78 

I have this JSON parse error when I try to submit a new member : 

ExceptionResolver : Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Can not construct instance of org.globe42.web.persons.CityDTO (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('42000 st-etienne'); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Can not construct instance of org.globe42.web.persons.CityDTO (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('42000 st-etienne')
 at [Source: (PushbackInputStream); line: 1, column: 154] (through reference chain: org.globe42.web.persons.PersonCommandDTO["city"])
![scrennshoterreurtech](https://user-images.githubusercontent.com/544206/28665982-c95240d2-72c5-11e7-96e4-1ba45149d7fa.png)

**Comment by acrepet** [comment]
I think that I didn't have this error with #65

**Comment by cexbrayat** [comment]
`st-etienne` is not valid in my opinion. Did you add the cities in your database? If not, go to `/cities` and import the CSV. It will populate the cities in your database, and the autocompletion should work fine then.

**Comment by acrepet** [comment]
Yes I did it (the population of cities in my database), but I didn't use well the autocompletion I guess.
Now it's OK!

**Comment by cexbrayat** [comment]
Maybe we should add a validator on the field, to make it invalid if the city has not been autocompleted? What do you think @jnizet ?

**Comment by jnizet** [comment]
It's a real bug. But we don't need any validator: there's only once: required. The problem is simply that we didn't use the `editable` input of the typeahead, which only accepts values that have been selected from the popup. Adding it makes the model null, and thus the field invalid since it's required, if you edit the value in the field.

**Comment by jnizet** [comment]
Note that I'm about to send a PR.

**Comment by jnizet** [comment]
In fact, I think we should also clear the input if its model is null, on blur, to make it clear that there is in fact not value for this field. It's specially important if the field becomes non-required, because otherwise, there is no indication at all that the field value is invalid. We could also add an icon in the field. PR on the way.
